"""bulk ingestion decoupling: cover storage, attempts, upsert

Revision ID: 8d7f65e9339e
Revises: f53331345773
Create Date: 2026-08-24 15:26:13.057122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7f65e9339e'
down_revision: Union[str, None] = 'f53331345773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('cover_key', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('cover_status', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('visual_attempts', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_posts_comment_attempts_pending', 'posts', ['comment_attempts'], unique=False, postgresql_where=sa.text('comments IS NULL'))
    op.create_index('ix_posts_visual_attempts_pending', 'posts', ['visual_attempts'], unique=False, postgresql_where=sa.text('visual_description IS NULL'))
    op.create_unique_constraint('world_posts_post_id_key', 'world_posts', ['post_id'], schema='topology')
    op.drop_column('world_posts', 'engagement', schema='topology')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_posts', sa.Column('engagement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True), schema='topology')
    op.drop_constraint('world_posts_post_id_key', 'world_posts', schema='topology', type_='unique')
    op.drop_index('ix_posts_visual_attempts_pending', table_name='posts', postgresql_where=sa.text('visual_description IS NULL'))
    op.drop_index('ix_posts_comment_attempts_pending', table_name='posts', postgresql_where=sa.text('comments IS NULL'))
    op.drop_column('posts', 'visual_attempts')
    op.drop_column('posts', 'cover_status')
    op.drop_column('posts', 'cover_key')
    op.drop_column('posts', 'comment_attempts')
    # ### end Alembic commands ###
