"""crawl_queries ledger + posts.vlm_json

Revision ID: b4c1e7f20a91
Revises: 8d7f65e9339e
Create Date: 2026-08-28

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b4c1e7f20a91'
down_revision: Union[str, None] = '8d7f65e9339e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'crawl_queries',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        # Slug, not an FK to topology.worlds: those UUIDs are regenerated by
        # reseed-worlds, and the ledger must outlive a reseed. Slug is the
        # stable identity everything else already keys on.
        sa.Column('world_slug', sa.Text(), nullable=False),
        sa.Column('round_no', sa.Integer(), nullable=False),
        sa.Column('query_text', sa.Text(), nullable=False),
        sa.Column('intent', sa.Text(), nullable=False),
        sa.Column('rationale', sa.Text(), nullable=True),
        sa.Column('handles_found', sa.Integer(), server_default='0', nullable=False),
        sa.Column('new_handles', sa.Integer(), server_default='0', nullable=False),
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('executed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_crawl_queries_status', 'crawl_queries', ['world_slug', 'status'], unique=False)
    op.add_column('posts', sa.Column('vlm_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade() -> None:
    op.drop_column('posts', 'vlm_json')
    op.drop_index('ix_crawl_queries_status', table_name='crawl_queries')
    op.drop_table('crawl_queries')
